
  - name: install remi rereleasepo
    command: dnf install https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y


  - name: install remi repo
    command: dnf module enable redis:remi-6.2 -y

  - name: install redis
    dnf:
      name: redis
      state: present

  - name: enable remote access
    replace:
      path: /etc/redis/redis.conf
      regexp: "127.0.0.1"
      replace: "0.0.0.0"

  - name: restart redis
    service:
      name: redis
      state: restarted
      enabled: yes
